version: '3'
services:
  database:
    image: postgres:latest
    container_name: rotaexata
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - rotaexata
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  data:
networks:
  rotaexata:
    driver: bridge